//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eman_Dev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int id { get; set; }
        public string companyname { get; set; }
        public string branchname { get; set; }
        public string email_id { get; set; }
        public string fax_no { get; set; }
        public string phone_no { get; set; }
        public string company_logo { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> activeflg { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
